### ISSUE TITLE
Authorization sağlamak için gerekli token'i nasıl edinebiliriz ?

### ISSUE THREAD

**Issue by EmincanY** [tingirifistik/BTK_Akademi#2]
Mevcut kodlarındaki AUTHORIZATION değişkenine sağlamamız gereken token bilgisini BTK Akademi için nasıl elde edebiliriz ? Bunu da Readme'de açıklarsan daha faydalı ve kullanımı kolay olur. Teşekkürler

**Comment by tingirifistik** [comment]
kodda hala birkac sikinti var(hic kayit olmadigin bir kursa bu program uzerinden kayit olurken sorun cikiyor vb). Bu sebeple, tokeni nerden nasil alacagiz gibi seyleri kodu sorunsuz hale getirince readme kismina ekleyecegim. 
Yine de su an kullanmak istersiniz diye anlatayim:
tokeni almak icin--> btk akademiye giris yaptiktan sonra tarayici konsolunu acin, depolama sekmesinden cerezler kismina gelin, burada auth tokenini kopyalayin, programdaki token kismina yapistirin.

not: url sorulunca direkt kursun url'ini girin
